FROM node:17 AS build

COPY package.json /app/
COPY yarn.lock /app/

WORKDIR /app

RUN yarn

COPY . /app/

RUN yarn run build

FROM nginx

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
