FROM node:17

COPY package.json /app/
COPY yarn.lock /app/
COPY .flowconfig /app/
COPY .babelrc /app/
COPY ./public /app/public
COPY ./src /app/src

WORKDIR /app

RUN yarn install && \
    yarn build

EXPOSE 3000
