FROM python:3.8

COPY ./services/requirements.txt /app/services/requirements.txt

WORKDIR /app

RUN pip install -r services/requirements.txt

COPY ./services /app/services

CMD python3 services/webservice.py
