name: Build and Upload Docker image

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image_name:
          - frontend
          - api
          - assembler
          - enricher
        file:
          - Dockerfile-frontend
          - Dockerfile-api
          - Dockerfile-assembler
          - Dockerfile-enricher
        context:
          - frontend
          - services/api
          - services/go-importer
          - services/go-importer

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ matrix.context }}"
          file: Dockerfile-${{ matrix.file }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-${{ matrix.image_name }}:latest